language: php

php: ["5.3", "5.4", "5.5"]

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "Zy8n/eP9CgpDcB36YSr87X9rOow5FGKd+wlUlOdqbsQBDO6AP1u5yZqJPiUKeLwlq0WME88QKVZhBta+NhxiHiCC7Ags+I0w79LuBwtEOWqSgMEr/QkcgVeZQqE4XeQxQFyFNTkhrMCq/6IHYkmLniq6QIpbKhJBeBkiCTGnhx0="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
